"""Fast Groebner-basis backends: msolve and Singular, with sympy fallback.

sympy's pure-Python Buchberger caps out around ~15 unknowns on the Keller
systems of this repository (docs/SEARCH_213.md §5.3).  This module shells
out to compiled engines for the single query the searches need most:

    is_unit_ideal(polys, gens)  --  is 1 in the ideal (no common zero)?

Backends, in order of preference:

  * msolve  (submodule external/msolve, built locally; F4, exact over Q)
        msolve -g 2 prints the reduced grevlex Groebner basis; the unit
        ideal prints as "[1]:".
  * Singular (system install; slimgb/std)
  * sympy   (always available; slow)

All backends compute over Q with grevlex order, so answers agree; the
choice only affects speed.  Use backend="all" to cross-check engines
against each other on one query.
"""

from __future__ import annotations

import os
import re
import resource
import shutil
import subprocess
import tempfile

import sympy as sp

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MSOLVE = os.environ.get("JCQFT_MSOLVE",
                        os.path.join(_REPO, "external", "msolve", "msolve"))
SINGULAR = os.environ.get("JCQFT_SINGULAR",
                          shutil.which("Singular") or "Singular")

_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")


def _check_names(gens):
    for g in gens:
        if not _NAME_RE.match(str(g)):
            raise ValueError(f"variable name {g} not safe for all backends")


def _clear_denoms(f, gens):
    """Integer-coefficient polynomial generating the same ideal element."""
    P = sp.Poly(sp.expand(f), *gens, domain="QQ")
    _, P = P.clear_denoms()
    return P.as_expr()


def _poly_str(f, gens, power="^"):
    s = sp.StrPrinter({"order": "none"}).doprint(sp.expand(f))
    return s.replace("**", power).replace(" ", "")


def available_backends():
    out = ["sympy"]
    if os.path.isfile(MSOLVE) and os.access(MSOLVE, os.X_OK):
        out.insert(0, "msolve")
    if shutil.which(SINGULAR):
        out.insert(-1 if out[0] == "msolve" else 0, "singular")
    return out


def is_unit_ideal(polys, gens, backend="auto", timeout=None, threads=None):
    """True iff the ideal generated by polys is (1), i.e. no common zero
    over the algebraic closure.  Exact over Q for every backend.

    backend: "msolve" | "singular" | "sympy" | "auto" (first available) |
             "all" (run every available backend and demand agreement).
    timeout: seconds (msolve/singular only); TimeoutError on expiry.
    threads: msolve only (-t; F4 linear-algebra parallelism).  Default:
             JCQFT_MSOLVE_THREADS or all cores.
    """
    gens = list(gens)
    _check_names(gens)
    polys = [q for q in (sp.expand(f) for f in polys) if q != 0]
    if not polys:
        return False
    polys = [_clear_denoms(f, gens) for f in polys]

    if backend == "auto":
        backend = available_backends()[0]
    if backend == "all":
        results = {b: is_unit_ideal(polys, gens, b, timeout, threads)
                   for b in available_backends()}
        assert len(set(results.values())) == 1, f"backends disagree: {results}"
        return next(iter(results.values()))

    if backend == "msolve":
        return _msolve_is_unit(polys, gens, timeout, threads)
    if backend == "singular":
        return _singular_is_unit(polys, gens, timeout)
    if backend == "sympy":
        gb = sp.groebner(polys, *gens, order="grevlex")
        return list(gb.exprs) == [1]
    raise ValueError(f"unknown backend {backend!r}")


# Hard address-space cap for GB subprocesses.  F4 on the larger Keller
# systems can exceed physical RAM and freeze the machine (it did); a capped
# run dies with a MemoryError-style failure instead, which we surface as
# RuntimeError("... memory cap ...").  Override via JCQFT_GB_MEM_MB.
GB_MEM_MB = int(os.environ.get("JCQFT_GB_MEM_MB", 16000))


def _limit_memory():
    lim = GB_MEM_MB * 1024 * 1024
    resource.setrlimit(resource.RLIMIT_AS, (lim, lim))


def _run(cmd, timeout):
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=timeout, preexec_fn=_limit_memory)
    except subprocess.TimeoutExpired as e:
        raise TimeoutError(f"{cmd[0]} exceeded {timeout} s") from e
    if proc.returncode != 0:
        tail = (proc.stdout or "")[-300:] + (proc.stderr or "")[-300:]
        if proc.returncode < 0 or "alloc" in tail.lower():
            raise RuntimeError(
                f"{cmd[0]} died (likely the {GB_MEM_MB} MB memory cap): "
                f"{tail}")
        raise RuntimeError(f"{cmd[0]} failed:\n{tail}")
    return proc.stdout


def _msolve_is_unit(polys, gens, timeout, threads=None):
    """msolve -g 2: reduced grevlex GB over Q; unit ideal prints '[1]:'."""
    if threads is None:
        threads = int(os.environ.get("JCQFT_MSOLVE_THREADS",
                                     os.cpu_count() or 1))
    with tempfile.NamedTemporaryFile("w", suffix=".ms", delete=False) as fh:
        fh.write(",".join(map(str, gens)) + "\n0\n")
        fh.write(",\n".join(_poly_str(f, gens) for f in polys) + "\n")
        path = fh.name
    try:
        out = _run([MSOLVE, "-g", "2", "-t", str(threads), "-f", path],
                   timeout)
    finally:
        os.unlink(path)
    body = [ln.strip() for ln in out.splitlines()
            if ln.strip() and not ln.startswith("#")]
    return body[-1].rstrip(":") == "[1]"


def _singular_is_unit(polys, gens, timeout):
    """Singular std(); unit ideal reduces to the single generator 1."""
    script = (
        f"ring R = 0, ({','.join(map(str, gens))}), dp;\n"
        "ideal I = "
        + ",\n  ".join(_poly_str(f, gens) for f in polys) + ";\n"
        "ideal G = std(I);\n"
        "print(size(G));\n"
        "print(G[1]);\n"
        "quit;\n"
    )
    with tempfile.NamedTemporaryFile("w", suffix=".sing",
                                     delete=False) as fh:
        fh.write(script)
        path = fh.name
    try:
        out = _run([SINGULAR, "-q", path], timeout)
    finally:
        os.unlink(path)
    lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
    return lines[-2:] == ["1", "1"]  # size(G) == 1 and G[1] == 1


if __name__ == "__main__":
    x, y = sp.symbols("x y")
    for be in available_backends():
        assert is_unit_ideal([x, x - 1], [x, y], be) is True
        assert is_unit_ideal([x**2 + y**2 - 1, x - y], [x, y], be) is False
        assert is_unit_ideal([sp.Rational(1, 2) * x - 1, x - 2], [x, y],
                             be) is False
        print(f"[ok] backend {be}")
    print("available:", available_backends())
