"""C*-equivariant reduction for the weight system (2, -1, -3).

Source action  lam . (x, y, z) = (lam^2 x, y/lam, z/lam^3).

INVARIANT THEORY (all claims proved by assertion in scripts/search_213.py).
The invariant ring R is NOT free (unlike the (1,-1,-m) family):

    u1 = x*y^2,   u2 = x^2*y*z,   u3 = x^3*z^2,      u1*u3 = u2^2

-- the coordinate ring of an A_1 quadric cone.  A monomial x^i y^j z^k is
invariant iff 2i - j - 3k = 0; the exponent semigroup is generated by
(1,2,0), (2,1,1), (3,0,2), and every invariant monomial has the UNIQUE
normal form u1^a u2^b u3^c with b in {0,1}:

    b = j mod 2,   a = (j - b)/2,   c = (k - b)/2.

WEIGHT MODULES.  The space M_d of weight-d polynomials is an R-module:

    M_2   = x * R                       (free, rank 1)
    M_-1  = y * R  (+)  x*z * C[u3]     (monomials with j >= 1 / j = 0)
    M_-3  = z * R  (+)  y^3 * C[u1]     (monomials with k >= 1 / k = 0)

The full module structure is M_-1 = y*R + xz*R with syzygies
(u1, -u2)... explicitly u1*(xz) = u2*y and u2*(xz) = u3*y, and
M_-3 = z*R + y^3*R with u1^2*z = u2*y^3 and u1*u2*z = u3*y^3; the direct
sums above are the syzygy-free canonical slices (C depends on u3 only,
E on u1 only).

COMPONENT WEIGHTS.  For DF(0) to be invertible each variable must occur
linearly: x only in a weight-2 component, y in weight -1, z in weight -3.
The weights are distinct, so the component weights are forced to be a
permutation of (2, -1, -3); we fix the order.  Normal form of every
admissible equivariant candidate (no polynomiality side conditions --
every choice of polynomial data assembles to a polynomial map):

    F = ( x*A(u),  y*B(u) + x*z*C(u3),  z*D(u) + y^3*E(u1) ),
    DF(0) = diag(A(0), B(0), D(0)),     det DF(0) = A(0)*B(0)*D(0).

CHART REDUCTION (exact; the C* acts freely on {y != 0}).  On the dense
chart {x != 0, y != 0} use the slice parametrization

    Phi(t, p, q) = ( p/t^2,  t,  q*t^3/p^2 ),        t = y,  p = u1,  q = u2.

Then u o Phi = (p, q, q^2/p) exactly, and with the chart data

    at(p,q) = A(p, q, q^2/p),
    bt(p,q) = B(p, q, q^2/p) + (q/p)   * C(q^2/p),
    et(p,q) = (q/p^2) * D(p, q, q^2/p) +  E(p),

one has F o Phi = ( p*at/t^2,  t*bt,  t^3*et )  and  det DPhi = -t/p^2.
The chain rule det D(F o Phi) = (det DF o Phi) * det DPhi yields the

    REDUCED KELLER IDENTITY
    det DF  =  Delta(p, q)
            :=  p^2 * ( 2*(p*at)*J2(bt, et) + bt*J2(p*at, et)
                        - 3*et*J2(p*at, bt) ),

a rational function of the two invariant chart coordinates alone (J2 =
Jacobian in (p,q)).  The coefficients (2, 1, -3) are the t-exponents
(-2, 1, 3) of F o Phi in the general pattern
k1*S1*J2(S2,S3) - k2*S2*J2(S1,S3) + k3*S3*J2(S1,S2).  Hence

    det DF == kappa   <=>   numerator( Delta - kappa ) == 0   in C[p, q]

(the denominator is a pure power of p; the chart is dense in C^3).

ORBIFOLD MECHANISMS.  A free orbit over the cone point (p0, q0), p0 != 0:
  * 2:1  if bt = et = 0 != at there: the image (p0*at/t^2, 0, 0) lies on
    the target x-axis, whose C* stabilizer is Z2 (lam^2 = 1); the two
    preimages of a point are Phi(+t0,...) and Phi(-t0,...).
  * 3:1  if at = bt = 0 != et: image (0, 0, t^3*et) on the target z-axis,
    stabilizer Z3 (lam^3 = 1); preimages Phi(w^k t0, ...), w^3 = 1.
A hit of either kind on a Keller solution is automatically a
counterexample (Z3 would be a new monodromy class, cf.
docs/SEARCH_STRATEGIES.md par. 2).
"""

from __future__ import annotations

import sympy as sp

x, y, z = sp.symbols("x y z")
u1, u2, u3 = sp.symbols("u1 u2 u3")
p, q, t = sp.symbols("p q t")

SOURCE_WEIGHTS = (2, -1, -3)

U_OF_XYZ = {u1: x * y**2, u2: x**2 * y * z, u3: x**3 * z**2}
RELATION = u1 * u3 - u2**2                      # == 0 on C^3
PHI_SUBS = {x: p / t**2, y: t, z: q * t**3 / p**2}   # slice chart, {x,y != 0}
CHART_SUBS = {u1: p, u2: q, u3: q**2 / p}            # u o Phi


def weight_of(i, j, k):
    """C*-weight of the monomial x^i y^j z^k."""
    return 2 * i - j - 3 * k


def semigroup_decompose(i, j, k):
    """(a, b, c) with u1^a u2^b u3^c = x^i y^j z^k and b in {0, 1};
    None if the monomial is not invariant.  This is the unique normal
    form (uniqueness proved in scripts/search_213.py)."""
    if weight_of(i, j, k) != 0:
        return None
    b = j % 2
    a, c = (j - b) // 2, (k - b) // 2
    if a < 0 or c < 0:
        return None
    return a, b, c


def to_normal_form(expr):
    """Invariant polynomial in (x, y, z)  ->  normal form in (u1, u2, u3),
    linear in u2.  Raises if some monomial is not invariant."""
    expr = sp.expand(expr)
    if expr == 0:
        return sp.S.Zero
    out = sp.S.Zero
    for (i, j, k), cf in sp.Poly(expr, x, y, z).terms():
        dec = semigroup_decompose(i, j, k)
        if dec is None:
            raise ValueError(f"non-invariant monomial x^{i} y^{j} z^{k}")
        a, b, c = dec
        out += cf * u1**a * u2**b * u3**c
    return sp.expand(out)


def normalize_u(expr):
    """Reduce a polynomial in (u1, u2, u3) to the normal form linear in u2
    (replace u2^2 -> u1*u3 repeatedly)."""
    expr = sp.expand(expr)
    while True:
        reduced = sp.expand(expr.subs(u2**2, u1 * u3))
        if reduced == expr:
            return expr
        expr = reduced


def assemble(A, B, C, D, E):
    """The equivariant map F = (x*A, y*B + x*z*C, z*D + y^3*E) as a
    polynomial map in (x, y, z).  A, B, C, D, E are polynomials in the
    invariants (u1, u2, u3); ANY choice assembles to a polynomial map."""
    A, B, C, D, E = [sp.sympify(f).subs(U_OF_XYZ) for f in (A, B, C, D, E)]
    return (sp.expand(x * A),
            sp.expand(y * B + x * z * C),
            sp.expand(z * D + y**3 * E))


def extract(F3, extra_syms=()):
    """Canonical module data (A, B, C, D, E) of an equivariant map:
    A, B, D in u2-normal form, C in C[u3], E in C[u1].  Asserts that each
    component is weight-homogeneous of weight (2, -1, -3)."""
    allowed = set(extra_syms)
    out = []
    for comp, d in zip(F3, SOURCE_WEIGHTS):
        comp = sp.expand(comp)
        assert not (comp.free_symbols - {x, y, z} - allowed), \
            f"unexpected symbols in {comp}"
        parts = {"gen0": sp.S.Zero, "gen1": sp.S.Zero}
        for (i, j, k), cf in sp.Poly(comp, x, y, z).terms():
            assert weight_of(i, j, k) == d, \
                f"component not weight-homogeneous of weight {d}"
            if d == 2:                       # M_2 = x*R
                dec = semigroup_decompose(i - 1, j, k)
                parts["gen0"] += cf * u1**dec[0] * u2**dec[1] * u3**dec[2]
            elif d == -1:                    # M_-1 = y*R (+) xz*C[u3]
                if j >= 1:
                    dec = semigroup_decompose(i, j - 1, k)
                    parts["gen0"] += cf * u1**dec[0] * u2**dec[1] * u3**dec[2]
                else:
                    dec = semigroup_decompose(i - 1, j, k - 1)
                    parts["gen1"] += cf * u1**dec[0] * u2**dec[1] * u3**dec[2]
            else:                            # M_-3 = z*R (+) y^3*C[u1]
                if k >= 1:
                    dec = semigroup_decompose(i, j, k - 1)
                    parts["gen0"] += cf * u1**dec[0] * u2**dec[1] * u3**dec[2]
                else:
                    dec = semigroup_decompose(i, j - 3, k)
                    parts["gen1"] += cf * u1**dec[0] * u2**dec[1] * u3**dec[2]
        if d == 2:
            out.append(sp.expand(parts["gen0"]))
        else:
            out.extend([sp.expand(parts["gen0"]), sp.expand(parts["gen1"])])
    return tuple(out)   # (A, B, C, D, E)


def chart(A, B, C, D, E):
    """Slice-chart data (at, bt, et) as rational functions of (p, q)."""
    At, Bt, Ct, Dt, Et = [sp.sympify(f).subs(CHART_SUBS)
                          for f in (A, B, C, D, E)]
    return (sp.together(At),
            sp.together(Bt + q / p * Ct),
            sp.together(q / p**2 * Dt + Et))


def j2(f, g):
    """Jacobian of (f, g) with respect to the chart coordinates (p, q)."""
    return sp.diff(f, p) * sp.diff(g, q) - sp.diff(f, q) * sp.diff(g, p)


def delta_chart(at, bt, et):
    """Reduced det DF as a rational function of (p, q):
    Delta = p^2 (2 p at J2(bt,et) + bt J2(p at, et) - 3 et J2(p at, bt))."""
    pa = p * at
    return p**2 * (2 * pa * j2(bt, et) + bt * j2(pa, et)
                   - 3 * et * j2(pa, bt))


def keller_numerator(at, bt, et, kappa):
    """Polynomial N(p, q) with Delta - kappa = N / p^s:
    N == 0  <=>  det DF == kappa identically on C^3."""
    diff = sp.cancel(sp.together(delta_chart(at, bt, et) - kappa))
    num, den = sp.fraction(diff)
    den = sp.expand(den)
    assert not den.has(q), f"denominator not a power of p: {den}"
    return sp.expand(num)


def det_df(F3):
    """Direct 3D Jacobian determinant (for cross-checks)."""
    J = sp.Matrix([[sp.diff(Fi, s) for s in (x, y, z)] for Fi in F3])
    return sp.expand(J.det())


def det_df_normal_form(A, B, C, D, E):
    """det DF as a normal-form polynomial in (u1, u2, u3) -- the intrinsic
    reduced determinant on the quadric cone (computed via the 3D det and
    the toric rewriting; equals delta_chart on the chart)."""
    return to_normal_form(det_df(assemble(A, B, C, D, E)))


# ---------------------------------------------------------------------------
# The two Keller families of the degree-1 box (proved complete in
# scripts/search_213.py): both are families of TAME AUTOMORPHISMS.
# ---------------------------------------------------------------------------

def family_V1(h0, h1):
    """Elementary z-shears  z -> z + y^3*(h0 + h1*u1):
    module data (A, B, C, D, E) of an automorphism (u1 is F-invariant)."""
    return (sp.S.One, sp.S.One, sp.S.Zero, sp.S.One, h0 + h1 * u1)


def family_V2(lam, nu):
    """Shears along the weight-(-1) invariant w = x*z - nu*y:
        F = (x, y + lam*x*w^3, z + lam*nu*w^3),      w o F = w,
    with explicit inverse (x, y - lam*x*w^3, z - lam*nu*w^3).  In the
    triangular coordinates (x, w, z) this is an elementary shear, so the
    family is tame.  Module data (A, B, C, D, E)."""
    return (sp.S.One,
            1 - lam * nu**3 * u1 + 3 * lam * nu**2 * u2 - 3 * lam * nu * u3,
            lam * u3,
            1 + 3 * lam * nu**3 * u1 - 3 * lam * nu**2 * u2 + lam * nu * u3,
            -lam * nu**4 + 0 * u1)


# ---------------------------------------------------------------------------
# Orbifold (non-injectivity) mechanisms
# ---------------------------------------------------------------------------

def orbit_point(t0, p0, q0):
    """The point Phi(t0, p0, q0) in C^3 (requires p0 != 0)."""
    return tuple(sp.simplify(c.subs({t: t0, p: p0, q: q0}))
                 for c in (p / t**2, t, q * t**3 / p**2))


def mechanism_witnesses(at, bt, et):
    """Solve the 2:1 locus {bt = et = 0, at != 0} and the 3:1 locus
    {at = bt = 0, et != 0} on {p != 0}.  Returns a dict
    {"2:1": [(p0, q0), ...], "3:1": [...]} of exact witnesses."""
    out = {"2:1": [], "3:1": []}
    for key, (f, g, h) in (("2:1", (bt, et, at)), ("3:1", (at, bt, et))):
        nf = sp.numer(sp.together(f))
        ng = sp.numer(sp.together(g))
        try:
            sols = sp.solve([nf, ng], [p, q], dict=True)
        except Exception:
            sols = []
        for s in sols:
            p0, q0 = s.get(p), s.get(q)
            if p0 is None or q0 is None:
                continue
            if p0.free_symbols or q0.free_symbols:
                continue
            if p0 == 0:
                continue
            hval = sp.simplify(h.subs({p: p0, q: q0}))
            if hval != 0:
                out[key].append((sp.nsimplify(p0), sp.nsimplify(q0)))
    return out
