"""Exactly which observables are missing from im F*?

(Resolves the loose end of docs/QFT_IMPLICATIONS.md §4.3(a): the claim that
F* is a monomorphism-not-automorphism is upgraded to an explicit, verified
structure theorem.  Write-up in docs/MISSING_OBSERVABLES.md.)

Results, all exact (sympy):

1.  y and z are rational in (x, F): substituting a -> F1, b -> F2, c -> F3
    into the fiber parametrization y = -B/(2 D0), z = -D/(8 D0) recovers y, z
    identically.  Hence C(x,y,z) = C(a,b,c)(x) after a -> F1, etc.
2.  The eliminant cubic p X^3 + q X + r is irreducible over C(a,b,c), so
    {1, x, x^2} is a BASIS of C(x,y,z) over (the fraction field of) im F*.
3.  NORMAL FORM: every polynomial observable O(x,y,z) is uniquely
        O = c0(F) + c1(F) x + c2(F) x^2,   ci rational with D0(F)-power
    denominators; O is fiber-symmetric iff c1 = c2 = 0.  The missing
    observables are generated by {x, x^2}: exactly the sheet separators.
4.  NO FINITE MODULE STRUCTURE: x is NOT integral over C[a,b,c] — along the
    exact escape curve phi(T) = (T, y0, (2T - 3T^2 y0 - c3)/T^3) the source
    escapes while F(phi(T)) stays bounded (limit computed exactly), which is
    impossible for an integral element.  Non-properness = non-finiteness of
    the ring extension; the basis in (2)-(3) is a field-level (equivalently,
    localized-at-D0) statement, not a polynomial-module one.
5.  Polynomial-level membership in im F* = C[F1,F2,F3]: every element of
    im F* is constant on fibers, and the exact fiber over (1,2,3) has three
    points with pairwise-distinct x, y, AND z coordinates — so none of
    x, y, z lies in im F* (nor in its fraction field).  Positive example
    by construction.  (The tag-variable Groebner test is the general
    decision procedure but is far too slow on this ideal.)
6.  Exhaustiveness of the finite-fiber description: for EVERY target the
    finite preimages are exactly the roots of the eliminant cubic with
    (y, z) determined by the parametrization (D0 != 0) or by direct solve
    (D0 = 0); spot-checked exactly on and off all special loci.
"""

import time

import sympy as sp

from jcqft.core import D0, F, PHI, SRC, cubic, p, q, r, X
from jcqft.fibers import exact_fiber, y_of_x, z_of_x

x, y, z = PHI
a, b, c = SRC

t0 = time.time()
SUB_F = {a: F[0], b: F[1], c: F[2]}


def check(label, cond):
    assert cond, label
    print(f"  [ok] {label}   ({time.time() - t0:.1f} s)")


print("== 1. y, z are rational in (x, F) — substitution identities ==")
check("y == y_of_x(x, F(phi))",
      sp.simplify(sp.together(y_of_x.subs(SUB_F)) - y) == 0)
check("z == z_of_x(x, F(phi))",
      sp.simplify(sp.together(z_of_x.subs(SUB_F)) - z) == 0)
check("x satisfies its eliminant: p(F) x^3 + q(F) x + r(F) == 0",
      sp.expand(cubic.subs(X, x).subs(SUB_F)) == 0)

print("== 2. cubic irreducible over C(a,b,c): {1,x,x^2} is a basis ==")
K = sp.QQ.frac_field(a, b, c)
check("eliminant irreducible over C(a,b,c)",
      sp.Poly(cubic, X, domain=K).is_irreducible)


print("== 3. normal form O = c0(F) + c1(F) x + c2(F) x^2 ==")


def normal_form(O):
    """(c0, c1, c2) in C(a,b,c) with O(x,y,z) == c0(F) + c1(F)x + c2(F)x^2.

    Substitute the fiber parametrization, then reduce mod the eliminant
    cubic over the fraction field C(a,b,c)."""
    Ohat = sp.together(O.subs({y: y_of_x, z: z_of_x}))
    num, den = sp.fraction(sp.cancel(Ohat))
    assert not den.has(x), f"denominator depends on x: {den}"
    rem = sp.Poly(num, x, domain=K).rem(sp.Poly(cubic.subs(X, x), x, domain=K))
    coeffs = rem.all_coeffs()  # highest degree first, deg(rem) <= 2
    coeffs = [sp.S.Zero] * (3 - len(coeffs)) + [sp.sympify(str(cf))
                                                for cf in coeffs]
    return tuple(sp.cancel(cf / den) for cf in reversed(coeffs))  # (c0,c1,c2)


def nf_verifies(O, cs):
    lhs = O - (cs[0] + cs[1] * x + cs[2] * x**2).subs(SUB_F)
    return sp.simplify(sp.together(lhs)) == 0


for label, O, expect in [
    ("x        -> (0, 1, 0)", x, (0, 1, 0)),
    ("x^2      -> (0, 0, 1)", x**2, (0, 0, 1)),
    ("F1       -> (a, 0, 0)", F[0], (a, 0, 0)),
    ("F3^2-5F2 -> (c^2-5b, 0, 0)", F[2] ** 2 - 5 * F[1],
     (c**2 - 5 * b, 0, 0)),
]:
    cs = normal_form(O)
    check(f"normal form {label}",
          all(sp.simplify(ci - ei) == 0 for ci, ei in zip(cs, expect)))

cs_y = normal_form(y)
check("normal form of y verifies as identity in (x,y,z)", nf_verifies(y, cs_y))
check("y is MISSING from im F* (c1, c2 not both 0)",
      not (cs_y[1] == 0 and cs_y[2] == 0))
cs_z = normal_form(z)
check("normal form of z verifies as identity in (x,y,z)", nf_verifies(z, cs_z))
check("z is MISSING from im F* (c1, c2 not both 0)",
      not (cs_z[1] == 0 and cs_z[2] == 0))
print("    y:", tuple(sp.factor(ci) for ci in cs_y))
print("    z:", tuple(sp.factor(ci) for ci in cs_z))

# uniqueness = linear independence of {1, x, x^2} over C(a,b,c), which is
# irreducibility (2); cross-check: a nontrivial relation would make the
# normal form of 0 nonzero.
check("uniqueness sanity: normal_form(0) == (0,0,0)",
      normal_form(sp.S.Zero) == (0, 0, 0))

print("== 4. x is NOT integral over im F*: exact escape certificate ==")
T, y0, c3 = sp.symbols("T y_0 c_3")
phi_T = (T, y0, (2 * T - 3 * T**2 * y0 - c3) / T**3)
FT = [sp.cancel(Fi.subs(dict(zip(PHI, phi_T)))) for Fi in F]
check("third component held constant: F3(phi(T)) == c3",
      sp.simplify(FT[2] - c3) == 0)
lims = [sp.limit(Fi, T, sp.oo) for Fi in FT]
check("F1, F2 have FINITE limits as T -> oo (x = T escapes): polynomials "
      "in (y0, c3)",
      all(not lim.has(T, sp.oo, sp.zoo, sp.nan)
          and lim.as_poly(y0, c3) is not None for lim in lims[:2]))
print("    lim F(phi(T)) =", tuple(sp.factor(l) for l in lims[:2]) + (c3,))
wall_p = sp.factor(p.subs(dict(zip(SRC, [lims[0], lims[1], c3]))))
check("the limit target lies ON the wall {p = 0}", sp.simplify(wall_p) == 0)

print("== 5. membership in im F*: fiber-separation certificate ==")
# Any O in im F* (even in the fraction field, wherever defined) is constant
# on fibers of F.  Exhibit one exact fiber whose 3 points have pairwise
# distinct x, y and z coordinates: none of x, y, z can lie in im F*.
fib123 = exact_fiber(tuple(Fi.subs({x: 1, y: 2, z: 3}) for Fi in F))
check("fiber over F(1,2,3) has 3 exact points", len(fib123) == 3)
for i, coord in enumerate("xyz"):
    vals = [pt[i] for pt in fib123]
    check(f"{coord}-coordinates pairwise distinct on the fiber => "
          f"{coord} NOT in im F*",
          len(set(vals)) == 3)
# positive example, by construction:
check("F1^2 F2 + 3 F3 - 7 IS in C[F] (trivially, by composition)",
      sp.expand((F[0] ** 2 * F[1] + 3 * F[2] - 7)
                - (a**2 * b + 3 * c - 7).subs(SUB_F)) == 0)

print("== 6. finite-fiber description is exhaustive (spot checks) ==")


def maps_back(pt, target):
    """Exact check F(pt) == target for points with algebraic (CRootOf)
    coordinates: replace the common root by a symbol and reduce the residual
    numerator modulo the root's minimal polynomial."""
    residuals = [Fi.subs(dict(zip(PHI, pt))) - ti
                 for Fi, ti in zip(F, target)]
    roots = set().union(*(res.atoms(sp.CRootOf) for res in residuals))
    if not roots:
        return all(sp.simplify(res) == 0 for res in residuals)
    assert len(roots) == 1
    rt = roots.pop()
    s = sp.Dummy("s")
    minpoly = sp.Poly(rt.expr.subs(rt.poly.gens[0], s), s)
    for res in residuals:
        num, _ = sp.fraction(sp.cancel(sp.together(res.subs(rt, s))))
        if sp.Poly(num, s).rem(minpoly) != 0:
            return False
    return True


# generic target (p != 0, D0 != 0), image point, wall target (p = 0),
# cusp orbit point: fiber sizes 3 / 3 / <=2 / 0.
for label, target, n_expect in [
    ("generic target (p = 171 != 0)", (1, 2, 3), 3),
    ("image of a rational point (consistency)",
     tuple(Fi.subs({x: 1, y: 2, z: 3}) for Fi in F), 3),
    ("wall p=0, generic (escaping pair gone, 1 finite point)",
     (sp.Rational(2, 27), 1, 1), 1),
    ("cusp orbit (empty fiber)", (sp.Rational(4, 27), sp.Rational(4, 3), 1), 0),
]:
    fib = exact_fiber(target)
    check(f"fiber over {label}: {len(fib)} points (expected {n_expect}), "
          "all map back to the target",
          len(fib) == n_expect and all(maps_back(pt, target) for pt in fib))

print(f"\nall checks passed in {time.time() - t0:.1f} s")
