"""Numerical monodromy of the degree-3 covering defined by the
Alpöge–Mathew counterexample map F : C^3 -> C^3.

Method
------
Restrict the covering to a generic complex line J(t) = J0 + t*v in target
space.  The fiber over J(t) consists of the 3 roots of the x-eliminant cubic
p*X^3 + q*X + r (with p, q, r evaluated at J(t)) together with the rational
y, z coordinates.  The covering restricted to the line is singular exactly at
the roots of

    p(J(t)) = 0            (true branch locus: sheets escape to infinity), and
    (4q^3 + 27pr^2)(J(t)) = 0   (two distinct fiber points share an
                                 x-coordinate; covering unramified there).

We transport the FULL 3-point fiber around closed loops encircling each
singular t by Newton predictor-corrector continuation on the exact system
F(phi) = J(t) (det DF = -2 identically, so Newton is uniformly
well-conditioned), match the transported fiber against the base fiber, and
read off a permutation per loop.  The subgroup of S3 generated by all loop
permutations is the (geometric) monodromy group of the covering.

Run:  .venv/bin/python monodromy.py       (takes ~1-2 minutes)
"""

from __future__ import annotations

import random
import sys
import time
from dataclasses import dataclass, field

import mpmath as mp
import sympy as sp

from jcqft import F, PHI, SRC, X, cubic, p, q, r

WALL0 = time.time()

x, y, z = PHI
a, b, c = SRC
tsym = sp.Symbol("t")

DPS = 30                      # working precision (decimal digits)
N_CIRCLE = 400                # steps per circle
RES_TOL_REPORT = mp.mpf("1e-20")   # required tracking accuracy

s_expr = 4 * q**3 + 27 * p * r**2      # x-collision factor of disc_X(cubic)
D0 = 27 * a * c**2 - 9 * b * c + 8    # denominator of the y,z parametrization
# NB: s_expr = 4 * D0**2 identically (verified below), so the x-collision
# locus is exactly {D0 = 0} and we loop around roots of the square-free D0.
assert sp.expand(s_expr - 4 * D0**2) == 0

mp.mp.dps = DPS

# --------------------------------------------------------------------------
# Rational fiber parametrization from the lex Groebner basis:
#   y = -B/A,  z = -D/C  with  A = 2*D0,  C = 8*D0  independent of x.
# --------------------------------------------------------------------------
print("computing lex Groebner basis (rational y,z parametrization) ...")
gb = sp.groebner([F[0] - a, F[1] - b, F[2] - c], y, z, x, order="lex")
g_y = next(g for g in gb.exprs if sp.degree(g, y) == 1)
g_z = next(g for g in gb.exprs if sp.degree(g, z) == 1)
A_, B_ = sp.Poly(g_y, y).all_coeffs()          # A*y + B = 0
C_, D_ = sp.Poly(g_z, z).all_coeffs()          # C*z + D = 0
assert sp.expand(A_ - 2 * D0) == 0 and sp.expand(C_ - 8 * D0) == 0

# fast numeric callables (mpmath)
f_F = sp.lambdify(PHI, list(F), "mpmath")
f_DF = sp.lambdify(PHI, sp.Matrix(F).jacobian(sp.Matrix(PHI)).tolist(), "mpmath")
f_pqr = sp.lambdify(SRC, [p, q, r], "mpmath")
f_yz = sp.lambdify((x, a, b, c), [-B_ / A_, -D_ / C_], "mpmath")


def rat2mp(v) -> mp.mpf:
    v = sp.Rational(v)
    return mp.mpf(int(v.p)) / int(v.q)


# --------------------------------------------------------------------------
# Choose a generic line J(t) = J0 + t*v.
# --------------------------------------------------------------------------
SEED = int(sys.argv[1]) if len(sys.argv) > 1 else 20260720


def choose_line():
    rng = random.Random(SEED)
    for _ in range(500):
        J0 = tuple(sp.Rational(rng.randint(-9, 9), rng.randint(1, 9)) for _ in range(3))
        v = tuple(sp.Rational(rng.randint(-9, 9), rng.randint(1, 9)) for _ in range(3))
        sub = dict(zip(SRC, [J0[i] + tsym * v[i] for i in range(3)]))
        vals = dict(zip(SRC, J0))
        if p.subs(vals) == 0 or s_expr.subs(vals) == 0 or D0.subs(vals) == 0:
            continue
        pt = sp.Poly(sp.expand(p.subs(sub)), tsym)
        st = sp.Poly(sp.expand(D0.subs(sub)), tsym)
        if pt.degree() != 4 or st.degree() != 3:
            continue
        # square-free, and no common roots (so p != 0 at all D0-roots)
        if sp.degree(sp.gcd(pt, pt.diff(tsym)), tsym) > 0:
            continue
        if sp.degree(sp.gcd(st, st.diff(tsym)), tsym) > 0:
            continue
        if sp.degree(sp.gcd(pt, st), tsym) > 0:
            continue
        return J0, v, pt, st
    raise RuntimeError("no generic line found")


def poly_roots_mp(poly: sp.Poly) -> list[mp.mpc]:
    coeffs = [rat2mp(cf) for cf in poly.all_coeffs()]
    return [mp.mpc(rt) for rt in mp.polyroots(coeffs, maxsteps=200, extraprec=100)]


J0, v, pt_poly, st_poly = choose_line()
J0m = [mp.mpc(rat2mp(u)) for u in J0]
vm = [mp.mpc(rat2mp(u)) for u in v]


def Jt(t: mp.mpc) -> list[mp.mpc]:
    return [J0m[i] + t * vm[i] for i in range(3)]


p_roots = poly_roots_mp(pt_poly)
s_roots = poly_roots_mp(st_poly)
all_roots = p_roots + s_roots

# --------------------------------------------------------------------------
# Newton corrector and base fiber.
# --------------------------------------------------------------------------
NEWTON_TOL = mp.mpf(10) ** (-(DPS - 8))


def newton(guess, target, maxit: int = 15):
    """Newton iteration on F(phi) = target.  Returns (phi, residual) or None."""
    phi = [mp.mpc(g) for g in guess]
    for _ in range(maxit):
        Fv = f_F(*phi)
        res = mp.matrix([Fv[i] - target[i] for i in range(3)])
        rn = mp.norm(res)
        if rn < NEWTON_TOL:
            return phi, rn
        try:
            dphi = mp.lu_solve(mp.matrix(f_DF(*phi)), res)
        except ZeroDivisionError:
            return None
        phi = [phi[i] - dphi[i] for i in range(3)]
    return None


def base_fiber() -> list[list[mp.mpc]]:
    pv, qv, rv = f_pqr(*J0m)
    xs = mp.polyroots([pv, mp.mpf(0), qv, rv], maxsteps=200, extraprec=100)
    pts = []
    for xr in xs:
        yr, zr = f_yz(mp.mpc(xr), *J0m)
        sol = newton([xr, yr, zr], J0m)
        assert sol is not None, "Newton polish of base fiber failed"
        pts.append(sol[0])
    # deterministic sheet labels: sort by (Re x, Im x)
    pts.sort(key=lambda P: (mp.re(P[0]), mp.im(P[0])))
    return pts


def dist(P, Q) -> mp.mpf:
    return mp.sqrt(sum(abs(P[i] - Q[i]) ** 2 for i in range(3)))


# --------------------------------------------------------------------------
# Predictor-corrector continuation with adaptive bisection.
# --------------------------------------------------------------------------
@dataclass
class Tracker:
    steps_taken: int = 0
    max_residual: mp.mpf = field(default_factory=lambda: mp.mpf(0))

    def step(self, sheets, t_from, t_to, depth: int = 0):
        """Advance all sheets from t_from to t_to; bisect on trouble."""
        if depth > 14:
            raise RuntimeError("continuation step failed after 14 bisections")
        target = Jt(t_to)
        dt = t_to - t_from
        sep_old = min(dist(sheets[i], sheets[j])
                      for i in range(3) for j in range(i + 1, 3))
        new = []
        ok = True
        for phi in sheets:
            try:  # tangent predictor: DF * dphi = v * dt
                dphi = mp.lu_solve(mp.matrix(f_DF(*phi)),
                                   mp.matrix([vm[i] * dt for i in range(3)]))
            except ZeroDivisionError:
                ok = False
                break
            guess = [phi[i] + dphi[i] for i in range(3)]
            sol = newton(guess, target)
            # corrector must stay well inside the sheet's basin
            if sol is None or dist(sol[0], guess) > 0.2 * sep_old:
                ok = False
                break
            new.append(sol[0])
            self.max_residual = max(self.max_residual, sol[1])
        if ok:
            sep_new = min(dist(new[i], new[j])
                          for i in range(3) for j in range(i + 1, 3))
            if sep_new < mp.mpf("1e-8"):
                ok = False    # possible sheet collision/jump -> refine
        if not ok:
            mid = (t_from + t_to) / 2
            sheets = self.step(sheets, t_from, mid, depth + 1)
            return self.step(sheets, mid, t_to, depth + 1)
        self.steps_taken += 1
        return new

    def track(self, ts, sheets):
        for k in range(len(ts) - 1):
            sheets = self.step(sheets, ts[k], ts[k + 1])
        return sheets


def loop_ts(center: mp.mpc, radius: mp.mpf, n_circle: int = N_CIRCLE):
    """Basepoint 0 -> circle start -> full CCW circle -> back to 0.

    The circle start is chosen so that the approach segment [0, start] stays
    as far as possible from all other singularities."""
    others = [u for u in all_roots if abs(u - center) > 1e-12]
    best = None
    for k in range(120):
        cand = center + radius * mp.expjpi(mp.mpf(2 * k) / 120)
        dmin = min(seg_dist(u, mp.mpc(0), cand) for u in others)
        # penalize approach segments that re-enter the circle
        if seg_dist(center, mp.mpc(0), cand) < radius * mp.mpf("0.999"):
            continue
        if best is None or dmin > best[0]:
            best = (dmin, cand)
    start = best[1]
    ang0 = mp.arg(start - center)
    n_seg = max(60, min(300, int(n_circle * abs(start) / (2 * mp.pi * radius))))
    seg = [start * mp.mpf(k) / n_seg for k in range(n_seg + 1)]
    circle = [center + radius * mp.expjpi((ang0 + 2 * mp.pi * k / n_circle) / mp.pi)
              for k in range(1, n_circle + 1)]
    return seg + circle + seg[::-1][1:]


def seg_dist(u: mp.mpc, z0: mp.mpc, z1: mp.mpc) -> mp.mpf:
    """Distance from the point u to the segment [z0, z1]."""
    d = z1 - z0
    s = mp.re((u - z0) * mp.conj(d)) / abs(d) ** 2
    s = min(mp.mpf(1), max(mp.mpf(0), s))
    return abs(u - (z0 + s * d))


def big_loop_ts(R: mp.mpf, n_circle: int = 2 * N_CIRCLE):
    """Circle |t| = R around everything.  The radial segment from the
    basepoint must not pass near a root of p(t) (there a sheet escapes;
    crossing the harmless D0 locus would be fine, but avoid it anyway)."""
    best = None
    for k in range(180):
        start = R * mp.expjpi(mp.mpf(2 * k) / 180)
        dmin = min(seg_dist(u, mp.mpc(0), start) for u in all_roots)
        if best is None or dmin > best[0]:
            best = (dmin, start)
    start = best[1]
    ang0 = mp.arg(start)
    n_seg = max(60, int(n_circle / (2 * mp.pi)))
    seg = [start * mp.mpf(k) / n_seg for k in range(n_seg + 1)]
    circle = [R * mp.expjpi((ang0 + 2 * mp.pi * k / n_circle) / mp.pi)
              for k in range(1, n_circle + 1)]
    return seg + circle + seg[::-1][1:]


# --------------------------------------------------------------------------
# Permutations.
# --------------------------------------------------------------------------
def match_permutation(base, moved) -> tuple[int, ...]:
    """perm[i] = j  <=>  sheet starting at base[i] returns at base[j]."""
    perm = []
    for m in moved:
        ds = sorted(range(3), key=lambda j: dist(m, base[j]))
        d0, d1 = dist(m, base[ds[0]]), dist(m, base[ds[1]])
        if not (d0 < mp.mpf("1e-10") and d1 > 1000 * d0):
            raise RuntimeError(
                f"ambiguous sheet matching: d0={mp.nstr(d0, 5)}, d1={mp.nstr(d1, 5)}")
        perm.append(ds[0])
    if sorted(perm) != [0, 1, 2]:
        raise RuntimeError(f"matching is not a bijection: {perm}")
    return tuple(perm)


def cycle_notation(perm: tuple[int, ...]) -> str:
    seen, cycles = set(), []
    for i in range(3):
        if i in seen:
            continue
        cyc, j = [i], perm[i]
        seen.add(i)
        while j != i:
            cyc.append(j)
            seen.add(j)
            j = perm[j]
        if len(cyc) > 1:
            cycles.append("(" + " ".join(str(k + 1) for k in cyc) + ")")
    return "".join(cycles) if cycles else "id"


def compose(p1, p2):
    """(p1 after p2)[i] = p1[p2[i]]."""
    return tuple(p1[p2[i]] for i in range(3))


def generated_group(gens):
    elems = {(0, 1, 2)} | set(gens)
    while True:
        new = {compose(g, h) for g in elems for h in elems} - elems
        if not new:
            return elems
        elems |= new


GROUP_NAMES = {1: "trivial group", 2: "Z/2 (a single transposition)",
               3: "A3 (cyclic of order 3)", 6: "S3 (full symmetric group)"}


def run_loop(center: mp.mpc, radius: mp.mpf, base):
    t0 = time.time()
    tracker = Tracker()
    moved = tracker.track(loop_ts(center, radius), [list(P) for P in base])
    perm = match_permutation(base, moved)
    print(f"  t* = {mp.nstr(center, 6):<26} radius {mp.nstr(radius, 4):<9} "
          f"perm = {cycle_notation(perm):<8} [{tracker.steps_taken} steps, "
          f"max|F(phi)-J| = {mp.nstr(tracker.max_residual, 3)}, "
          f"{time.time() - t0:.1f} s]")
    assert tracker.max_residual < RES_TOL_REPORT
    return perm


# --------------------------------------------------------------------------
# Main.
# --------------------------------------------------------------------------
def main():
    print("\n=== Monodromy of the Alpöge–Mathew covering (degree 3) ===")
    print(f"line J(t) = J0 + t*v with J0 = {J0}, v = {v}   (seed {SEED})")
    print(f"precision: mp.dps = {DPS}, {N_CIRCLE} steps per circle\n")

    print(f"branch factor      p(J(t)):  degree {pt_poly.degree()}, roots")
    for rt in p_roots:
        print(f"    t = {mp.nstr(rt, 12)}")
    print("collision factor: 4q^3+27pr^2 = 4*D0^2 with D0 = 27ac^2-9bc+8;")
    print(f"  D0(J(t)):  degree {st_poly.degree()}, roots")
    for rt in s_roots:
        print(f"    t = {mp.nstr(rt, 12)}")

    base = base_fiber()
    print("\nbase fiber over J0 (t = 0), sheets labelled 1..3:")
    for i, P in enumerate(base):
        print(f"  sheet {i + 1}: ({', '.join(mp.nstr(u, 10) for u in P)})")
    sep = min(dist(base[i], base[j]) for i in range(3) for j in range(i + 1, 3))
    print(f"  minimal sheet separation: {mp.nstr(sep, 4)}")

    def radius_for(center):
        d_other = min(abs(center - u) for u in all_roots if abs(center - u) > 1e-12)
        return mp.mpf("0.3") * min(d_other, abs(center) / mp.mpf("0.3") * mp.mpf("0.8"))

    gens = []
    print("\n--- loops around the branch locus {p = 0} ---")
    for rt in p_roots:
        gens.append(run_loop(rt, radius_for(rt), base))

    print("\n--- loops around the x-collision locus {4q^3 + 27pr^2 = 0} ---")
    for rt in s_roots[:2]:
        gens.append(run_loop(rt, radius_for(rt), base))

    print("\n--- big loop enclosing ALL singularities ---")
    R = 2 * max(abs(rt) for rt in all_roots)
    t0 = time.time()
    tracker = Tracker()
    moved = tracker.track(big_loop_ts(R), [list(P) for P in base])
    big_perm = match_permutation(base, moved)
    print(f"  |t| = {mp.nstr(R, 6)}: perm = {cycle_notation(big_perm):<8} "
          f"[{tracker.steps_taken} steps, "
          f"max|F(phi)-J| = {mp.nstr(tracker.max_residual, 3)}, "
          f"{time.time() - t0:.1f} s]")
    assert tracker.max_residual < RES_TOL_REPORT

    group = generated_group(gens)
    print("\n--- results ---")
    print(f"permutations found: {[cycle_notation(g) for g in gens]}")
    print(f"generated subgroup of S3: order {len(group)} -> "
          f"{GROUP_NAMES[len(group)]}")

    disc = sp.factor(sp.discriminant(cubic, X))
    fl = sp.factor_list(disc)
    odd = [f for f, e in fl[1] if e % 2 == 1]
    print(f"\nsymbolic cross-check: disc_X(cubic) = {sp.sstr(disc)}")
    print(f"  square in C(a,b,c)? {'yes' if not odd else 'NO'}"
          + (f"  (odd-multiplicity factors: {[sp.sstr(f) for f in odd]})" if odd else ""))
    print("  -> Galois group of the x-cubic over Q(a,b,c) is S3;"
          " numerics above show the geometric monodromy realizes it."
          if odd else "  -> discriminant is a square: A3 expected.")

    print(f"\ntotal wall time: {time.time() - WALL0:.1f} s")


if __name__ == "__main__":
    main()
