"""Exact reduction and counterexample search for the weight system (2,-1,-3).

(The (2,-1,-3) analogue of scripts/reduction_113.py + the search of
scripts/search_counterexamples.py.  Machinery: jcqft/reduction_213.py;
write-up: docs/SEARCH_213.md.)

Default run (~2 min): proves every claimed identity by assertion, then
solves the Keller condition COMPLETELY in the degree-1 ansatz box and
classifies all solutions.  --full adds the larger "CE2" box no-go
(~8 min); --deg2 attempts the full degree-2 box (hours; skipped gracefully
on per-query timeout).

PROVED HERE, all exact:

1. INVARIANT THEORY.  R = C[x,y,z]^{C*} is generated by u1 = x*y^2,
   u2 = x^2*y*z, u3 = x^3*z^2 with the single relation u1*u3 = u2^2 (A_1
   cone); normal form u1^a u2^b u3^c, b in {0,1} (exhaustive in a degree
   box + uniqueness).  Weight modules:  M_2 = x*R,
   M_-1 = y*R (+) x*z*C[u3],  M_-3 = z*R (+) y^3*C[u1].
   DF(0) invertible forces component weights (2,-1,-3), DF(0) diagonal.

2. REDUCED KELLER IDENTITY (chart-based, dense chart {x,y != 0}).  With
   Phi(t,p,q) = (p/t^2, t, q t^3/p^2):  u o Phi = (p, q, q^2/p),
   F o Phi = (p*at/t^2, t*bt, t^3*et), det DPhi = -t/p^2, and
       det DF = Delta(p,q)
              = p^2 (2 p at J2(bt,et) + bt J2(p at, et) - 3 et J2(p at, bt)),
   proved with UNDETERMINED FUNCTIONS (bona fide identity of differential
   polynomials) and cross-checked on the fully symbolic degree-1 ansatz
   (3D determinant vs Delta).  det DF == kappa  <=>  the polynomial
   numerator of Delta - kappa vanishes.

3. SEARCH, DEGREE-1 BOX (A,B,D deg <= 1 in (u1,u2,u3), C = c3*u3,
   E = e0 + e1*u1; gauge A(0)=B(0)=D(0)=1 => kappa = 1, C(0) = 0).
   The Keller variety is 2-DIMENSIONAL and decomposes EXACTLY as
       V(I) = V1 u V2,
   V1 = elementary shears z -> z + y^3(e0 + e1 u1),
   V2 = shears along w = xz - nu*y:  (x, y + lam x w^3, z + lam nu w^3).
   Completeness is certified by ideal-membership (Groebner reduction)
   nilpotency certificates in the three strata {e1 != 0}, {c3 != 0},
   {e1 = c3 = 0}.  Both families are tame automorphisms (explicit
   inverses).  ==> NO counterexample; the box is RIGID: nonlinear Keller
   maps exist but are all tame automorphisms.

4. ORBIFOLD-MECHANISM NO-GO.  A 2:1 (resp. 3:1) hit needs a cone point
   (p0, q0), p0 != 0, with bt = et = 0 != at (resp. at = bt = 0 != et),
   or the analogous degeneration on the y = 0 stratum.  The residual
   2-torus gauge moves any witness to (1,1) or (1,0) (u3 = 1 on y = 0),
   so the pointwise Groebner emptiness checks below are exhaustive:
   ALL EMPTY in the degree-1 box, and (--full) in the CE2 box
   (A,B,D deg <= 1, C in span{u3,u3^2}, E in span{1,u1,u1^2}).
"""

from __future__ import annotations

import argparse
import itertools
import signal
import time
from concurrent.futures import ThreadPoolExecutor

import sympy as sp

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from jcqft.prefilter import infinity_prefilter          # noqa: E402
from jcqft.reduction_213 import (                        # noqa: E402
    CHART_SUBS, PHI_SUBS, RELATION, U_OF_XYZ, assemble, chart, delta_chart,
    det_df, det_df_normal_form, extract, family_V1, family_V2, j2,
    keller_numerator, mechanism_witnesses, orbit_point, p, q,
    semigroup_decompose, t, to_normal_form, u1, u2, u3, weight_of, x, y, z)

T0 = time.time()


def check(label, cond):
    assert cond, label
    print(f"  [ok] {label}   ({time.time() - T0:.1f} s)")


class TimeoutError_(Exception):
    pass


def with_timeout(seconds, fn, *args, **kwargs):
    """Run fn with a SIGALRM timeout; returns (True, result) or (False, None)."""
    def handler(signum, frame):
        raise TimeoutError_()
    old = signal.signal(signal.SIGALRM, handler)
    signal.alarm(seconds)
    try:
        out = fn(*args, **kwargs)
        return True, out
    except TimeoutError_:
        return False, None
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, old)


# ===========================================================================
print("== 1. invariant theory of lam.(x,y,z) = (lam^2 x, y/lam, z/lam^3) ==")
# ===========================================================================

check("relation u1*u3 - u2^2 == 0 in C[x,y,z]",
      sp.expand(RELATION.subs(U_OF_XYZ)) == 0)
check("U2^2 - U1*U3 is irreducible (A_1 quadric cone)",
      sp.factor_list(u2**2 - u1 * u3)[1][0][1] == 1
      and len(sp.factor_list(u2**2 - u1 * u3)[1]) == 1)

DEG = 12
inv_count, seen = 0, {}
for i, j, k in itertools.product(range(DEG + 1), repeat=3):
    if i + j + k > DEG or weight_of(i, j, k) != 0:
        continue
    dec = semigroup_decompose(i, j, k)
    assert dec is not None and dec[1] in (0, 1), (i, j, k)
    a, b, c = dec
    # reconstruction: u1^a u2^b u3^c == x^i y^j z^k
    assert (a + 2 * b + 3 * c, 2 * a + b, b + 2 * c) == (i, j, k)
    assert dec not in seen, "normal form not unique"
    seen[dec] = (i, j, k)
    inv_count += 1
check(f"all {inv_count} invariant monomials of degree <= {DEG} have a unique "
      "normal form u1^a u2^b u3^c, b in {0,1}", True)

mod_counts = {}
for d in (2, -1, -3):
    n = 0
    for i, j, k in itertools.product(range(DEG + 1), repeat=3):
        if i + j + k > DEG or weight_of(i, j, k) != d:
            continue
        n += 1
        if d == 2:            # M_2 = x*R
            assert i >= 1 and semigroup_decompose(i - 1, j, k), (i, j, k)
        elif d == -1:         # M_-1 = y*R (+) xz*C[u3]
            if j >= 1:
                assert semigroup_decompose(i, j - 1, k), (i, j, k)
            else:             # j = 0 => x^(3c+1) z^(2c+1) = xz*u3^c
                assert k >= 1 and i >= 1
                dec = semigroup_decompose(i - 1, j, k - 1)
                assert dec and dec[0] == 0 and dec[1] == 0, (i, j, k)
        else:                 # M_-3 = z*R (+) y^3*C[u1]
            if k >= 1:
                assert semigroup_decompose(i, j, k - 1), (i, j, k)
            else:             # k = 0 => x^a y^(2a+3) = y^3*u1^a
                assert j >= 3
                dec = semigroup_decompose(i, j - 3, k)
                assert dec and dec[1] == 0 and dec[2] == 0, (i, j, k)
    mod_counts[d] = n
check("module generators verified exhaustively (deg <= 12): "
      f"M_2 = x*R ({mod_counts[2]} monomials), "
      f"M_-1 = y*R + xz*C[u3] ({mod_counts[-1]}), "
      f"M_-3 = z*R + y^3*C[u1] ({mod_counts[-3]})", True)

# component weights: x/y/z have weights 2/-1/-3; DF(0) invertible needs each
# variable linear in some component, and a linear monomial of weight d only
# fits in a weight-d component => weights are a permutation of (2,-1,-3).
check("linear monomials have pairwise distinct weights (2, -1, -3) => "
      "component weights forced, DF(0) diagonal",
      len({weight_of(1, 0, 0), weight_of(0, 1, 0), weight_of(0, 0, 1)}) == 3)

# ===========================================================================
print("== 2. reduced Keller identity (chart {x, y != 0}) ==")
# ===========================================================================

check("u o Phi == (p, q, q^2/p)",
      all(sp.cancel(U_OF_XYZ[u].subs(PHI_SUBS) - CHART_SUBS[u]) == 0
          for u in (u1, u2, u3)))
Phi = tuple(PHI_SUBS[s] for s in (x, y, z))
dPhi = sp.Matrix([[sp.diff(cmp_, s) for s in (t, p, q)] for cmp_ in Phi])
check("det DPhi == -t/p^2", sp.cancel(dPhi.det() + t / p**2) == 0)

Af, Bf, Df = [sp.Function(n) for n in "ABD"]
Cf, Ef = sp.Function("C"), sp.Function("E")
UX = (x * y**2, x**2 * y * z, x**3 * z**2)
F_gen = (x * Af(*UX),
         y * Bf(*UX) + x * z * Cf(UX[2]),
         z * Df(*UX) + y**3 * Ef(UX[0]))
at_g = Af(p, q, q**2 / p)
bt_g = Bf(p, q, q**2 / p) + q / p * Cf(q**2 / p)
et_g = q / p**2 * Df(p, q, q**2 / p) + Ef(p)
check("F o Phi == (p*at/t^2, t*bt, t^3*et) for UNDETERMINED functions",
      all(sp.simplify(Fi.subs(PHI_SUBS) - Ti) == 0 for Fi, Ti in
          zip(F_gen, (p * at_g / t**2, t * bt_g, t**3 * et_g))))

S1, S2, S3 = [sp.Function(n)(p, q) for n in ("S1", "S2", "S3")]
G3 = (S1 / t**2, t * S2, t**3 * S3)
dG = sp.Matrix([[sp.diff(Gi, s) for s in (t, p, q)] for Gi in G3])
check("det dG == t*(-2 S1 J2(S2,S3) - S2 J2(S1,S3) + 3 S3 J2(S1,S2)) "
      "for UNDETERMINED functions",
      sp.simplify(dG.det() - t * (-2 * S1 * j2(S2, S3) - S2 * j2(S1, S3)
                                  + 3 * S3 * j2(S1, S2))) == 0)

dF_gen = sp.Matrix([[sp.diff(Fi, s) for s in (x, y, z)] for Fi in F_gen])
detF_chart = sp.simplify(dF_gen.det().subs(PHI_SUBS))
check("det DF o Phi == Delta(p,q) and is t-free (GENERIC-FUNCTION PROOF of "
      "the reduced Keller identity)",
      sp.simplify(detF_chart - delta_chart(at_g, bt_g, et_g)) == 0
      and not detF_chart.has(t))

# fully symbolic degree-1 ansatz: 3D determinant == Delta(u1, u2) exactly
SY = sp.symbols("a1 a2 a3 b1 b2 b3 c3 d1 d2 d3 e0 e1")
a1, a2, a3, b1, b2, b3, c3, d1, d2, d3, e0, e1 = SY
A1 = 1 + a1 * u1 + a2 * u2 + a3 * u3
B1 = 1 + b1 * u1 + b2 * u2 + b3 * u3
C1 = c3 * u3
D1 = 1 + d1 * u1 + d2 * u2 + d3 * u3
E1 = e0 + e1 * u1
F1box = assemble(A1, B1, C1, D1, E1)
at1, bt1, et1 = chart(A1, B1, C1, D1, E1)
check("deg-1 box, ALL coefficients symbolic: det DF (3D) == Delta(u1,u2)",
      sp.cancel(det_df(F1box)
                - delta_chart(at1, bt1, et1).subs({p: x * y**2,
                                                   q: x**2 * y * z})) == 0)
check("extract o assemble == id on the symbolic deg-1 data",
      extract(F1box, extra_syms=set(SY)) == tuple(
          sp.expand(f) for f in (A1, B1, C1, D1, E1)))
nf1 = det_df_normal_form(A1, B1, C1, D1, E1)
check("normal-form det on the cone agrees with Delta in the chart",
      sp.cancel(nf1.subs(CHART_SUBS) - delta_chart(at1, bt1, et1)) == 0)
check("sanity: identity map has Delta == 1",
      sp.cancel(delta_chart(*chart(1 + 0 * u1, sp.S.One, sp.S.Zero,
                                   sp.S.One, sp.S.Zero))) == 1)

# ===========================================================================
print("== 3. search, degree-1 box (gauge: A(0)=B(0)=D(0)=1, kappa=1, "
      "C(0)=0) ==")
# ===========================================================================

N1 = keller_numerator(at1, bt1, et1, 1)
keller_eqs = sp.Poly(N1, p, q).coeffs()
print(f"  Keller system: {len(keller_eqs)} coefficient equations, "
      f"{len(SY)} unknowns (trilinear in the (A | B,C | D,E) blocks)")

# the three linear equations force the A-block
lin = [e for e in keller_eqs if sp.total_degree(sp.Poly(e, *SY)) == 1]
sol_a = sp.solve(lin, [a1, a2, a3], dict=True)[0]
check("linear part of the system forces a1, a2, a3: "
      + ", ".join(f"{k} = {v}" for k, v in sol_a.items()),
      len(lin) == 3 and set(sol_a) == {a1, a2, a3})
eqs_r = [sp.expand(e.subs(sol_a)) for e in keller_eqs]
eqs_r = [sp.numer(sp.together(e)) for e in eqs_r if e != 0]
REST = [b1, b2, b3, c3, d1, d2, d3, e0, e1]

G = sp.groebner(eqs_r, *REST, order="grevlex")
lt_supports = [frozenset(v for v, e_ in zip(REST, g.monoms(order="grevlex")[0])
                         if e_) for g in G.polys]
dim = 0
for r_ in range(len(REST), 0, -1):
    if any(all(not sup <= set(S) for sup in lt_supports)
           for S in itertools.combinations(REST, r_)):
        dim = r_
        break
check(f"Keller variety: NOT empty, dimension {dim} (grevlex GB, "
      f"{len(G.exprs)} elements)", dim == 2 and not G.is_zero_dimensional)


def member(gb, f):
    return gb.reduce(sp.expand(f))[1] == 0


def nilcert(gb, f, cofactor=sp.S.One, kmax=14):
    fk = sp.S.One
    for k in range(1, kmax + 1):
        fk = sp.expand(fk * f)
        if member(gb, cofactor * fk):
            return k
    return None


print("  -- complete decomposition V(I) = V1 u V2 --")
# (ii) the families solve the system
for name, fam in (("V1 (z-shears)", family_V1(*sp.symbols("h0 h1"))),
                  ("V2 (w-shears)", family_V2(*sp.symbols("lam nu")))):
    check(f"{name}: Delta == 1 identically in the family parameters",
          sp.cancel(delta_chart(*chart(*fam))) == 1)

# (iii) completeness certificates
V2REL = [e1, b3 + 3 * d3, c3 * b2 - 3 * d3**2, c3 * d2 + 3 * d3**2,
         c3**2 * b1 + d3**3, c3**2 * d1 - 3 * d3**3, c3**3 * e0 + d3**4]
for f in V2REL[1:]:
    k = nilcert(G, f)
    check(f"({f})^{k} in I  => {f} == 0 on the WHOLE Keller variety",
          k is not None)
k = nilcert(G, e1, cofactor=c3)
check(f"c3*e1^{k} in I  => e1 == 0 wherever c3 != 0 "
      "(with the global relations: {c3 != 0} stratum = V2, lam = c3, "
      "nu = d3/c3)", k is not None)
for v in [b1, b2, b3, c3, d1, d2, d3]:
    k = nilcert(G, v, cofactor=e1)
    check(f"e1*{v}^{k} in I  => {v} == 0 wherever e1 != 0 "
          "({e1 != 0} stratum = V1)", k is not None)
G0 = sp.groebner(eqs_r + [c3, e1], *REST, order="grevlex")
for v in [b1, b2, b3, d1, d2, d3]:
    k = nilcert(G0, v)
    check(f"{v}^{k} in I + (c3, e1)  => {v} == 0 on the {{c3 = e1 = 0}} "
          "stratum (= V1 with e1 = 0)", k is not None)
print("  => COMPLETE: every Keller map of the box lies in V1 or V2")

print("  -- classification: both families are tame automorphisms --")
h0, h1, lam, nu = sp.symbols("h0 h1 lam nu")
FV1 = assemble(*family_V1(h0, h1))
inv1 = (x, y, z - y**3 * (h0 + h1 * x * y**2))
check("V1 inverse: (x, y, z - y^3(h0 + h1 u1)) o F == id",
      tuple(sp.expand(i.subs(dict(zip((x, y, z), FV1)), simultaneous=True))
            for i in inv1) == (x, y, z))
FV2 = assemble(*family_V2(lam, nu))
w_inv = x * z - nu * y
inv2 = (x, y - lam * x * w_inv**3, z - lam * nu * w_inv**3)
check("V2 preserves w = xz - nu*y and (x, y - lam x w^3, z - lam nu w^3) "
      "o F == id (elementary shear in the triangular coords (x, w, z))",
      sp.expand(FV2[0] * FV2[2] - nu * FV2[1] - w_inv) == 0 and
      tuple(sp.expand(i.subs(dict(zip((x, y, z), FV2)), simultaneous=True))
            for i in inv2) == (x, y, z))

for label, data in (("V1 sample (e0,e1)=(2,-1)", family_V1(sp.Integer(2), sp.Integer(-1))),
                    ("V2 sample (lam,nu)=(1,1)", family_V2(sp.S.One, sp.S.One))):
    Fs = assemble(*data)
    ats, bts, ets = chart(*data)
    wits = mechanism_witnesses(ats, bts, ets)
    tgt = (sp.Rational(3, 7), sp.Rational(-2, 5), sp.Rational(1, 3))
    fib = sp.solve([Fs[i] - tgt[i] for i in range(3)], [x, y, z], dict=True)
    check(f"{label}: det DF == 1, no 2:1/3:1 witness, generic fiber has "
          f"exactly {len(fib)} point (injective), infinity prefilter "
          f"survives={infinity_prefilter(Fs, (x, y, z))} (known "
          "false-positive class: nonlinear automorphisms)",
          det_df(Fs) == 1 and wits == {"2:1": [], "3:1": []}
          and len(fib) == 1)

# ===========================================================================
print("== 4. orbifold-mechanism no-go (2:1 and 3:1), degree-1 box ==")
# ===========================================================================
# gauge: the residual torus (u1, u2, u3) -> (m1 u1, m2 u2, m2^2/m1 u3)
# acts freely on witness points (p0, q0), p0 != 0: any q0 != 0 witness
# moves to (1,1), any q0 = 0 witness to (1,0); on the y = 0 stratum u3
# scales freely, so u3 = 1.  Emptiness at these points is exhaustive.

r_ = sp.Symbol("r")


def wit_at(f, P0, Q0):
    return sp.expand(sp.numer(sp.together(f)).subs({p: P0, q: Q0}))


def mech_queries(A_, B_, C_, D_, E_, keller):
    at_, bt_, et_ = chart(A_, B_, C_, D_, E_)
    sub_y0 = {u1: 0, u2: 0, u3: 1}
    return {
        "2:1 @ (p,q)=(1,1)": keller + [wit_at(bt_, 1, 1), wit_at(et_, 1, 1),
                                       1 - r_ * wit_at(at_, 1, 1)],
        "2:1 @ (p,q)=(1,0)": keller + [wit_at(bt_, 1, 0), wit_at(et_, 1, 0),
                                       1 - r_ * wit_at(at_, 1, 0)],
        "3:1 @ (p,q)=(1,1)": keller + [wit_at(at_, 1, 1), wit_at(bt_, 1, 1),
                                       1 - r_ * wit_at(et_, 1, 1)],
        "3:1 @ (p,q)=(1,0)": keller + [wit_at(at_, 1, 0), wit_at(bt_, 1, 0),
                                       1 - r_ * wit_at(et_, 1, 0)],
        "2:1 @ y=0, u3=1": keller + [C_.subs(sub_y0), D_.subs(sub_y0),
                                     1 - r_ * A_.subs(sub_y0)],
        "3:1 @ y=0, u3=1": keller + [A_.subs(sub_y0), C_.subs(sub_y0),
                                     1 - r_ * D_.subs(sub_y0)],
    }


for label, sys_ in mech_queries(A1, B1, C1, D1, E1, keller_eqs).items():
    gbq = sp.groebner(sys_, *(list(SY) + [r_]), order="grevlex")
    check(f"{label}: Groebner basis == [1], NO such Keller map in the box",
          list(gbq.exprs) == [1])

print("\nDEGREE-1 BOX VERDICT: nonlinear Keller maps exist (two 2-parameter"
      "\nfamilies) but ALL are tame automorphisms; no non-injective Keller"
      "\nmap, and both orbifold mechanisms (Z2 and Z3) are provably empty.")


# ===========================================================================
# --full: CE2 box (A, B, D deg <= 1; C in span{u3, u3^2}; E in
#         span{1, u1, u1^2}) -- mechanism no-go, exact over Q
# ===========================================================================

def run_full():
    print("\n== 5. (--full) CE2 box mechanism no-go ==")
    cs = sp.symbols("c3 c6")
    es = sp.symbols("e0 e1 e2")
    C2 = cs[0] * u3 + cs[1] * u3**2
    E2 = es[0] + es[1] * u1 + es[2] * u1**2
    at2, bt2, et2 = chart(A1, B1, C2, D1, E2)
    N2 = keller_numerator(at2, bt2, et2, 1)
    unknowns2 = sorted(N2.free_symbols - {p, q}, key=str)
    keller2 = sp.Poly(N2, p, q).coeffs()
    print(f"  {len(unknowns2)} unknowns, {len(keller2)} Keller equations")
    for label, sys_ in mech_queries(A1, B1, C2, D1, E2, keller2).items():
        ok, gbq = with_timeout(1200, sp.groebner, sys_,
                               *(unknowns2 + [r_]), order="grevlex")
        if not ok:
            print(f"  [timeout] {label} (>1200 s, skipped)")
            continue
        check(f"CE2 {label}: Groebner basis == [1], NO such Keller map",
              list(gbq.exprs) == [1])
    print("  CE2 VERDICT: no 2:1/3:1 orbifold-mechanism counterexample in"
          "\n  the CE2 box either.  (Full variety decomposition of CE2 not"
          "\n  attempted: sympy Groebner too slow beyond ~15 unknowns.)")


# ===========================================================================
# --deg2: full degree-2 box (29 unknowns) -- via jcqft.gb_backend
#          (msolve/Singular; the sympy fallback needs hours).
# ===========================================================================

def run_deg2(budget, backend="auto", workers=1):
    from jcqft.gb_backend import available_backends, is_unit_ideal
    print("\n== 6. (--deg2) full degree-2 box ==")
    print(f"  GB backends available: {available_backends()} "
          f"(using {backend!r})")
    MON2 = [u1, u2, u3, u1**2, u1 * u3, u3**2, u1 * u2, u2 * u3]

    def gpoly(name, monos):
        return sp.Add(*[sp.Symbol(f"{name}{i}") * m
                        for i, m in enumerate(monos)])

    A_ = 1 + gpoly("A", MON2)
    B_ = 1 + gpoly("B", MON2)
    C_ = gpoly("C", [u3, u3**2])
    D_ = 1 + gpoly("D", MON2)
    E_ = gpoly("E", [1, u1, u1**2])
    at_, bt_, et_ = chart(A_, B_, C_, D_, E_)
    N_ = keller_numerator(at_, bt_, et_, 1)
    unknowns_ = sorted(N_.free_symbols - {p, q}, key=str)
    keller_ = sp.Poly(N_, p, q).coeffs()
    print(f"  {len(unknowns_)} unknowns, {len(keller_)} Keller equations; "
          f"budget {budget} s per query")
    queries = mech_queries(A_, B_, C_, D_, E_, keller_)
    # concurrency is MEMORY-bound: one of these GB runs over Q can exceed
    # 10 GB, and more F4 threads enlarge the in-flight matrices.  Default
    # is strictly sequential; the per-process cap in jcqft.gb_backend
    # (JCQFT_GB_MEM_MB) turns a blow-up into a clean failure.
    n_par = min(len(queries), workers)
    t_each = max(1, (os.cpu_count() or 1) // (2 * n_par))
    print(f"  running {len(queries)} queries concurrently "
          f"({n_par} workers x {t_each} msolve threads)")
    unresolved = 0
    with ThreadPoolExecutor(max_workers=n_par) as pool:
        futs = {label: pool.submit(is_unit_ideal, sys_, unknowns_ + [r_],
                                   backend=backend, timeout=budget,
                                   threads=t_each)
                for label, sys_ in queries.items()}
        for label, fut in futs.items():
            try:
                empty = fut.result()
            except TimeoutError:
                print(f"  [timeout] {label} (> {budget} s) -- UNRESOLVED")
                unresolved += 1
                continue
            except RuntimeError as exc:
                print(f"  [failed] {label} -- UNRESOLVED ({exc})")
                unresolved += 1
                continue
            check(f"deg2 {label}: "
                  f"{'EMPTY (ideal = (1))' if empty else '??'}", empty)
    if unresolved == 0:
        print("  DEG2 VERDICT: no 2:1/3:1 orbifold-mechanism counterexample"
              "\n  in the FULL degree-2 box (29 unknowns), exact over Q.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--full", action="store_true",
                    help="add the CE2-box mechanism no-go (~8 min)")
    ap.add_argument("--deg2", action="store_true",
                    help="full degree-2 box (fast with msolve/Singular; "
                         "hours with the sympy fallback)")
    ap.add_argument("--deg2-budget", type=int, default=3600,
                    help="per-query timeout for --deg2 (s)")
    ap.add_argument("--gb-backend", default="auto",
                    help="msolve | singular | sympy | auto | all")
    ap.add_argument("--deg2-workers", type=int, default=1,
                    help="concurrent --deg2 queries (memory-bound: one "
                         "query can exceed 10 GB; keep at 1 unless you "
                         "have RAM to spare)")
    args = ap.parse_args()
    if args.full:
        run_full()
    if args.deg2:
        run_deg2(args.deg2_budget, args.gb_backend, args.deg2_workers)
    print(f"\nall checks passed in {time.time() - T0:.1f} s")
